import React from 'react';
import { Head, useForm } from '@inertiajs/react';
import { 
    FileText, 
    Upload, 
    CheckCircle, 
    AlertTriangle, 
    ShieldCheck,
    BookOpen,
    Scale
} from 'lucide-react';

// --- GLOBAL COMPONENTS ---
import NavBar from '@/components/app-header'; 
import Footer from '@/components/nav-footer'; 
import Breadcrumbs from '@/components/breadcrumbs'; 
import FileUpload from '@/components/file-upload'; 

// --- UI PRIMITIVES ---
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

interface PageProps {
    auth: {
        user: {
            name: string;
            role_in_group: 'Leader' | 'Member';
        };
    };
}

export default function IpPlagiarism({ auth }: PageProps) {
    const isLeader = auth.user.role_in_group === 'Leader';
    
    const { data, setData, post, processing, errors } = useForm({
        compliance_checked_1: false,
        compliance_checked_2: false,
        compliance_checked_3: false,
        plagiarism_report: null as File | null,
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        // post(route('student.ip.submit')); 
    };

    const allComplianceChecked = data.compliance_checked_1 && data.compliance_checked_2 && data.compliance_checked_3;

    return (
        <div className="min-h-screen bg-background flex flex-col">
            <Head title="IP & Plagiarism Compliance" />

            <NavBar user={auth.user} />

            <main className="flex-1 max-w-7xl w-full mx-auto px-4 py-6 space-y-6">
                
                <Breadcrumbs 
                    items={[
                        { label: 'Management', href: '#' },
                        { label: 'IP & Plagiarism', href: '#', active: true }
                    ]} 
                />

                {/* PAGE HEADER */}
                <div className="flex items-center gap-3">
                    <div className="bg-primary/10 p-3 rounded-md">
                        <FileText className="w-8 h-8 text-primary" />
                    </div>
                    <div>
                        <h1 className="text-3xl font-bold tracking-tight text-primary">IP & Plagiarism</h1>
                        <p className="text-muted-foreground">Manage thesis intellectual property and plagiarism checks.</p>
                    </div>
                </div>

                <div className="grid gap-6 md:grid-cols-12 h-full">
                    
                    {/* --- LEFT COLUMN: SUBMISSION FORM (7 Cols) --- */}
                    <div className="md:col-span-7 space-y-6">
                        
                        {/* Status Alert */}
                        <Alert variant="default" className="border-primary/50 bg-primary/5">
                            <AlertTriangle className="h-4 w-4 text-primary" />
                            <AlertTitle className="text-primary font-semibold">Compliance Pending</AlertTitle>
                            <AlertDescription>
                                Please upload your Plagiarism Report and sign the IP declaration below.
                            </AlertDescription>
                        </Alert>

                        <Card className="border-muted-foreground/20 shadow-sm">
                            <CardHeader className="bg-primary text-primary-foreground rounded-t-lg py-4">
                                <CardTitle className="text-lg flex items-center gap-2">
                                    <Upload className="h-5 w-5" />
                                    Submission & Verification
                                </CardTitle>
                            </CardHeader>
                            
                            <CardContent className="p-6 space-y-8">
                                {/* 1. FILE UPLOAD */}
                                <div className="space-y-3">
                                    <div className="flex items-center justify-between">
                                        <h3 className="text-sm font-semibold">1. Plagiarism Check Report</h3>
                                        <Badge variant="outline" className="bg-background">PDF Only</Badge>
                                    </div>
                                    <p className="text-xs text-muted-foreground">
                                        Upload the similarity report generated by the University's plagiarism checker.
                                        <span className="font-medium text-primary"> Max similarity accepted: 20%.</span>
                                    </p>
                                    
                                    <FileUpload 
                                        value={data.plagiarism_report}
                                        onChange={(file) => setData('plagiarism_report', file)}
                                        accept=".pdf"
                                        disabled={!isLeader}
                                        maxSizeMB={10}
                                    />
                                    {errors.plagiarism_report && (
                                        <p className="text-sm text-destructive font-medium">{errors.plagiarism_report}</p>
                                    )}
                                </div>

                                {/* 2. COMPLIANCE CHECKBOXES */}
                                <div className="space-y-4">
                                    <h3 className="text-sm font-semibold">2. Declaration of Compliance</h3>
                                    <div className="grid gap-4 p-4 border rounded-lg bg-muted/10">
                                        <div className="flex items-start space-x-3">
                                            <Checkbox 
                                                id="c1"
                                                checked={data.compliance_checked_1}
                                                onCheckedChange={(c) => setData('compliance_checked_1', !!c)}
                                                disabled={!isLeader}
                                            />
                                            <label htmlFor="c1" className="text-sm leading-tight peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                                                I certify that this manuscript is my/our original work and plagiarism check has been conducted.
                                            </label>
                                        </div>
                                        <div className="flex items-start space-x-3">
                                            <Checkbox 
                                                id="c2"
                                                checked={data.compliance_checked_2}
                                                onCheckedChange={(c) => setData('compliance_checked_2', !!c)}
                                                disabled={!isLeader}
                                            />
                                            <label htmlFor="c2" className="text-sm leading-tight peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                                                I have read and understood the University Intellectual Property (IP) Policy provided in the panel.
                                            </label>
                                        </div>
                                        <div className="flex items-start space-x-3">
                                            <Checkbox 
                                                id="c3"
                                                checked={data.compliance_checked_3}
                                                onCheckedChange={(c) => setData('compliance_checked_3', !!c)}
                                                disabled={!isLeader}
                                            />
                                            <label htmlFor="c3" className="text-sm leading-tight peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                                                I grant the University non-exclusive rights to archive and publish the abstract of this work.
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </CardContent>

                            <CardFooter className="bg-muted/5 py-4 border-t">
                                {isLeader ? (
                                    <Button 
                                        onClick={handleSubmit}
                                        className="w-full sm:w-auto ml-auto"
                                        disabled={!allComplianceChecked || processing}
                                    >
                                        {processing ? "Uploading..." : "Confirm & Submit Compliance"}
                                    </Button>
                                ) : (
                                    <Button variant="secondary" disabled className="w-full sm:w-auto ml-auto">
                                        Awaiting Leader Submission
                                    </Button>
                                )}
                            </CardFooter>
                        </Card>
                    </div>

                    {/* --- RIGHT COLUMN: FULL IP POLICY TEXT (5 Cols) --- */}
                    <div className="md:col-span-5 space-y-6">
                        <Card className="h-[750px] flex flex-col shadow-sm border-muted-foreground/20 overflow-hidden">
                            <CardHeader className="bg-muted/20 pb-4 border-b">
                                <CardTitle className="text-base flex items-center gap-2">
                                    <BookOpen className="w-5 h-5 text-primary" />
                                    Intellectual Property Policy
                                </CardTitle>
                                <CardDescription>
                                    Department of Computer Engineering
                                </CardDescription>
                            </CardHeader>
                            
                            {/* SCROLLABLE FULL TEXT AREA */}
                            <div className="flex-1 overflow-y-auto p-6 text-sm text-foreground space-y-6 leading-relaxed bg-white dark:bg-zinc-950">
                                
                                {/* ARTICLE I */}
                                <section>
                                    <h4 className="font-bold text-primary mb-3 text-base flex items-center gap-2">
                                        <Scale className="w-4 h-4" />
                                        Article I: Intellectual Property Rights
                                    </h4>
                                    
                                    <div className="space-y-4">
                                        <div>
                                            <strong className="block text-foreground mb-1">Section 1: Student Ownership</strong>
                                            <p className="text-muted-foreground text-justify">
                                                In accordance with the Intellectual Property Code of the Philippines (Republic Act No. 8293), the University recognizes that the student author(s) own the copyright of their thesis, dissertation, or capstone project, provided that the work was created independently without substantial use of University-funded research or institutional library/laboratory access beyond standard academic curriculum requirements. The student retains the moral and economic rights to their creation unless otherwise stipulated in a separate funding agreement.
                                            </p>
                                        </div>

                                        <div>
                                            <strong className="block text-foreground mb-1">Section 2: Co-Ownership</strong>
                                            <p className="text-muted-foreground text-justify">
                                                In cases where the thesis resulted from a project funded by the University (e.g., use of University resources, facilities, personnel, equipment, specific research grants, or substantial institutional laboratory access), the University shall retain joint ownership of the patent or copyright. Any income derived from the commercialization of such work shall be shared between the University and the student author(s) in accordance with the University's Technology Transfer guidelines.
                                            </p>
                                        </div>

                                        <div>
                                            <strong className="block text-foreground mb-1">Section 3: Commissioned Work</strong>
                                            <p className="text-muted-foreground text-justify">
                                                Works created by students at the specific direction and control of the University, or as part of an externally funded research project administered by the University, shall be owned by the University or the funding agency, as specified in the research contract.
                                            </p>
                                        </div>
                                    </div>
                                </section>

                                <div className="h-px bg-border my-2" />

                                {/* ARTICLE II */}
                                <section>
                                    <h4 className="font-bold text-primary mb-3 text-base flex items-center gap-2">
                                        <ShieldCheck className="w-4 h-4" />
                                        Article II: Institutional Repository Rights
                                    </h4>
                                    
                                    <p className="text-muted-foreground mb-3 text-justify">
                                        By submitting this manuscript and signing the compliance form, the author(s) grant the University a non-exclusive, worldwide, royalty-free, and perpetual license to:
                                    </p>
                                    
                                    <ul className="list-disc pl-5 space-y-2 text-muted-foreground">
                                        <li>
                                            <strong>Archive:</strong> Store the work in the University Library's digital and physical repository for long-term preservation.
                                        </li>
                                        <li>
                                            <strong>Access:</strong> Make the work accessible to the academic community, researchers, and the general public for educational and research purposes, subject to any embargo period requested by the author(s) for patent protection.
                                        </li>
                                        <li>
                                            <strong>Migration:</strong> Convert or migrate the work to any medium or format for the purpose of preservation, ensuring that the content remains readable and accessible as technology evolves.
                                        </li>
                                    </ul>
                                </section>

                                <div className="h-px bg-border my-2" />

                                {/* ARTICLE III */}
                                <section>
                                    <h4 className="font-bold text-primary mb-3 text-base flex items-center gap-2">
                                        <AlertTriangle className="w-4 h-4" />
                                        Article III: Plagiarism & Originality
                                    </h4>
                                    
                                    <div className="space-y-4">
                                        <div>
                                            <strong className="block text-foreground mb-1">Section 1: Definition</strong>
                                            <p className="text-muted-foreground text-justify">
                                                Plagiarism is defined as the appropriation of another person's ideas, processes, results, or words without giving appropriate credit. This includes the use of AI-generated content without proper disclosure and citation.
                                            </p>
                                        </div>
                                        <div>
                                            <strong className="block text-foreground mb-1">Section 2: Similarity Threshold</strong>
                                            <p className="text-muted-foreground text-justify">
                                                All thesis submissions must undergo a similarity check using the University-prescribed software (e.g., Turnitin). The acceptable similarity index is <strong>below 20%</strong>. Matches found in the bibliography, common phrases, and properly cited quotes may be excluded from the count at the discretion of the Research Coordinator.
                                            </p>
                                        </div>
                                    </div>
                                </section>

                                <div className="h-px bg-border my-2" />

                                {/* ARTICLE IV */}
                                <section>
                                    <h4 className="font-bold text-primary mb-3 text-base flex items-center gap-2">
                                        <BookOpen className="w-4 h-4" />
                                        Article IV: Sanctions
                                    </h4>
                                    <p className="text-muted-foreground text-justify">
                                        Any violation of these guidelines, including falsification of data, submission of plagiarized work, or infringement of copyright, shall be subject to disciplinary action in accordance with the Student Handbook and the University Code of Conduct. This may include a failing grade for the Capstone Project course, suspension, or expulsion.
                                    </p>
                                </section>

                                <div className="pt-6 text-center">
                                    <p className="text-xs text-muted-foreground italic">
                                        Last Updated: Academic Year 2024-2025<br/>
                                        Approved by the College of Engineering Research Council
                                    </p>
                                </div>
                            </div>
                        </Card>

                        {/* Certificate Preview */}
                        <Card className="bg-gradient-to-br from-muted/50 to-background border-dashed opacity-80">
                            <CardContent className="flex flex-col items-center justify-center p-6 text-center space-y-2">
                                <div className="h-12 w-12 rounded-full bg-muted text-muted-foreground flex items-center justify-center mb-2">
                                    <ShieldCheck className="w-6 h-6" />
                                </div>
                                <h4 className="font-semibold text-sm">Certificate of IP Compliance</h4>
                                <p className="text-xs text-muted-foreground">
                                    This certificate is automatically generated upon approval of your Plagiarism Report.
                                </p>
                            </CardContent>
                        </Card>
                    </div>

                </div>
            </main>

            <Footer />
        </div>
    );
}