import { Student } from './student_interface';

export const studentData: Student[] = [
  {
    studentNumber: "2022-00001-MN-0",
    name: "Rena Dela Cruz",
    email: "ronadelacruz@iskolarngbayan.pup.edu.ph",
    groupCode: "3I01",
    block: "BSCPE 3-1",
    specialization: "Machine Learning",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00002-MN-0",
    name: "John Santos",
    email: "johnsantos@iskolarngbayan.pup.edu.ph",
    groupCode: "3I01",
    block: "BSCPE 3-1",
    specialization: "Machine Learning",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00003-MN-0",
    name: "Maria Garcia",
    email: "mariagarcia@iskolarngbayan.pup.edu.ph",
    groupCode: "3I01",
    block: "BSCPE 3-1",
    specialization: "Machine Learning",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00004-MN-0",
    name: "Pedro Reyes",
    email: "pedroreyes@iskolarngbayan.pup.edu.ph",
    groupCode: "3I02",
    block: "BSCPE 3-3",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2022-00005-MN-0",
    name: "Ana Lopez",
    email: "analopez@iskolarngbayan.pup.edu.ph",
    groupCode: "3I02",
    block: "BSCPE 3-3",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00006-MN-0",
    name: "Carlos Mendoza",
    email: "carlosmendoza@iskolarngbayan.pup.edu.ph",
    groupCode: "3I02",
    block: "BSCPE 3-3",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00007-MN-0",
    name: "Sofia Torres",
    email: "sofiatorres@iskolarngbayan.pup.edu.ph",
    groupCode: "4I01",
    block: "BSCPE 4-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00008-MN-0",
    name: "Miguel Cruz",
    email: "miguelcruz@iskolarngbayan.pup.edu.ph",
    groupCode: "4I01",
    block: "BSCPE 4-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2022-00009-MN-0",
    name: "Isabella Ramos",
    email: "isabellaramos@iskolarngbayan.pup.edu.ph",
    groupCode: "4I01",
    block: "BSCPE 4-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00010-MN-0",
    name: "Luis Fernandez",
    email: "luisfernandez@iskolarngbayan.pup.edu.ph",
    groupCode: "4I02",
    block: "BSCPE 4-2",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2022-00011-MN-0",
    name: "Carmen Diaz",
    email: "carmendiaz@iskolarngbayan.pup.edu.ph",
    groupCode: "4I02",
    block: "BSCPE 4-2",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00012-MN-0",
    name: "Rafael Silva",
    email: "rafaelsilva@iskolarngbayan.pup.edu.ph",
    groupCode: "4I02",
    block: "BSCPE 4-2",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00013-MN-0",
    name: "Elena Martinez",
    email: "elenamartinez@iskolarngbayan.pup.edu.ph",
    groupCode: "4I03",
    block: "BSCPE 4-1",
    specialization: "Machine Learning",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00014-MN-0",
    name: "Diego Morales",
    email: "diegomorales@iskolarngbayan.pup.edu.ph",
    groupCode: "4I03",
    block: "BSCPE 4-1",
    specialization: "Machine Learning",
    adviser: "Dr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2022-00015-MN-0",
    name: "Lucia Herrera",
    email: "luciaherrera@iskolarngbayan.pup.edu.ph",
    groupCode: "4I03",
    block: "BSCPE 4-1",
    specialization: "Machine Learning",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00016-MN-0",
    name: "Antonio Vargas",
    email: "antoniovargas@iskolarngbayan.pup.edu.ph",
    groupCode: "4I04",
    block: "BSCPE 4-6",
    specialization: "System Development",
    adviser: "Engr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2022-00017-MN-0",
    name: "Gabriela Ortiz",
    email: "gabrielaortiz@iskolarngbayan.pup.edu.ph",
    groupCode: "4I04",
    block: "BSCPE 4-6",
    specialization: "System Development",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00018-MN-0",
    name: "Fernando Castro",
    email: "fernandocastro@iskolarngbayan.pup.edu.ph",
    groupCode: "4I04",
    block: "BSCPE 4-6",
    specialization: "System Development",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00019-MN-0",
    name: "Valentina Ruiz",
    email: "valentinaruiz@iskolarngbayan.pup.edu.ph",
    groupCode: "3I03",
    block: "BSCPE 3-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00020-MN-0",
    name: "Sebastian Flores",
    email: "sebastianflores@iskolarngbayan.pup.edu.ph",
    groupCode: "3I03",
    block: "BSCPE 3-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2021-00021-MN-0",
    name: "Camila Jimenez",
    email: "camilajimenez@iskolarngbayan.pup.edu.ph",
    groupCode: "3I03",
    block: "BSCPE 3-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00022-MN-0",
    name: "Mateo Gonzalez",
    email: "mateogonzalez@iskolarngbayan.pup.edu.ph",
    groupCode: "3I04",
    block: "BSCPE 3-4",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00023-MN-0",
    name: "Natalia Romero",
    email: "nataliaromero@iskolarngbayan.pup.edu.ph",
    groupCode: "3I04",
    block: "BSCPE 3-4",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2022-00024-MN-0",
    name: "Alejandro Suarez",
    email: "alejandrosuarez@iskolarngbayan.pup.edu.ph",
    groupCode: "3I04",
    block: "BSCPE 3-4",
    specialization: "Big Data Analytics",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00025-MN-0",
    name: "Victoria Ramirez",
    email: "victoriaramirez@iskolarngbayan.pup.edu.ph",
    groupCode: "4I05",
    block: "BSCPE 4-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2022-00026-MN-0",
    name: "Daniel Medina",
    email: "danielmedina@iskolarngbayan.pup.edu.ph",
    groupCode: "4I05",
    block: "BSCPE 4-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00027-MN-0",
    name: "Andrea Guzman",
    email: "andreaguzman@iskolarngbayan.pup.edu.ph",
    groupCode: "4I05",
    block: "BSCPE 4-3",
    specialization: "Big Data Analytics",
    adviser: "Dr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00028-MN-0",
    name: "Pablo Rivera",
    email: "pablorivera@iskolarngbayan.pup.edu.ph",
    groupCode: "4I06",
    block: "BSCPE 4-5",
    specialization: "Computer Networks",
    adviser: "Engr. Robert Dela Cruz",
  },
  {
    studentNumber: "2022-00029-MN-0",
    name: "Laura Nunez",
    email: "lauranunez@iskolarngbayan.pup.edu.ph",
    groupCode: "4I06",
    block: "BSCPE 4-5",
    specialization: "Computer Networks",
    adviser: "Engr. Robert Dela Cruz",
    hasPhoto: true,
  },
  {
    studentNumber: "2022-00030-MN-0",
    name: "Javier Campos",
    email: "javiercampos@iskolarngbayan.pup.edu.ph",
    groupCode: "4I06",
    block: "BSCPE 4-5",
    specialization: "Computer Networks",
    adviser: "Engr. Robert Dela Cruz",
  },
];

export const thesisTitles: { [key: string]: string } = {
  "3I01": "AI-Powered Predictive Analytics for Student Performance",
  "3I02": "Cloud-Based Data Visualization Dashboard for IoT Sensors",
  "3I03": "Real-Time Traffic Monitoring Using Big Data Analytics",
  "3I04": "Sentiment Analysis of Social Media Posts Using NLP",
  "4I01": "Automated Image Classification for Medical Diagnostics",
  "4I02": "Smart Recommendation System for E-Commerce Platforms",
  "4I03": "Deep Learning for Facial Recognition Security Systems",
  "4I04": "Web-Based Inventory Management System with QR Integration",
  "4I05": "Predictive Maintenance System for Industrial Equipment",
  "4I06": "Application of AI for Intrusion Detection"
};